const AUBERGINE = '#636BF6'
const AUBERGINE_DARK = '#474db8'
const MINT = '#57BA9F'
const MINT_DARK = '#529986'
const AUBERGINE_PALE = '#B0B1F9'

const MIDNIGHT_0 = '#0A182A'
const MIDNIGHT_1 = '#142136'
const MIDNIGHT_2 = '#1a283e'
const MIDNIGHT_3 = '#253955'
const MIDNIGHT_4 = '#2F4666'
const MIDNIGHT_5 = '#415470'

export const SMOKE = '#DADEE3'
export const WHITE = '#FFFFFF'

// ELEMENTS
export const BACKGROUND = MIDNIGHT_0
export const BACKGROUND_MEDIUM = MIDNIGHT_1
export const BACKGROUND_LIGHT = MIDNIGHT_2

export const ACCENT = AUBERGINE
export const ACCENT_DARK = AUBERGINE_DARK
export const SECONDARY_ACCENT = MINT
export const SECONDARY_ACCENT_DARK = MINT_DARK

// TEXT
export const TEXT_LIGHT = WHITE
export const TEXT_LIGHT_MUTED = SMOKE
export const TEXT_DARK = MIDNIGHT_1
export const TEXT_DARK_MUTED = MIDNIGHT_2
